import pytest

@pytest.mark.failed
def test_3():
    assert 2==4

def test_4():
    assert 4==4
